name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build -x lint -x test
